### ISSUE TITLE
Git config alias for deleting stale branches

### ISSUE THREAD

**Issue by spences10** [spences10/dotfiles#2]
https://github.com/spences10/cheat-sheets/blob/master/sheets/git.md#delete-branches

https://cheat-sheets.ss10.dev/git/#delete-branches

**Comment by eclectic-coding** [comment]
Broken link.

**Comment by spences10** [comment]
It's been moved to here: https://cheat-sheets.ss10.dev/git/

But! As there's no header links just yet you can find it here: https://github.com/spences10/cheat-sheets/blob/master/sheets/git.md#delete-branches 🙃

**Comment by spences10** [comment]
@polishedwp this has been fixed in both the cheat sheets site and updated the main issue link
